### ISSUE TITLE
High memory usage in vscode but not with vim

### ISSUE THREAD

**Issue by agauniyal** [richard1122/vscode-youcompleteme#32]
Hi again,
I'm having trouble with simple code that makes use of boost libs, I expected it to take much memory than naive c++ code. When I use vim and ycm plugin, it take about 10% of my system memory which is expected, but when I use vscode and this plugin, it takes about 50% of my system memory on the same source file and doing same things. So the difference in memory consumption is about 5x in both plugins.

I think that this plugin might be processing something extra behind the scenes which is making it consume much more memory, can you please check why it does so?

**Comment by agauniyal** [comment]
And it's not this plugin's process that takes memory, its the ycm process itself. So it seems this plugin is sending some extra data to ycm process that vim plugin doesn't?

**Comment by richard1122** [comment]
I'm not sure.
I'm trying to make all API calls the same as what vim using. 
Could you please provide more log and create an issue to YCMD project ? 
I'm glad to offer any help.

**Comment by agauniyal** [comment]
I don't think YCMD is the issue here because vim plugin works fine and takes ~10% memory. How to provide logs regarding this - do you need the debug logs? Maybe this plugin is requesting more data other than simple completion which vim plugin doesn't?

Let me explain it more clearly -

 - I open a cpp source file with vim, do `XYZ` changes in it. The peak memory is 10%-11%. I undo the `XYZ` changes.
 - I open the same cpp source file with vscode, do the same `XYZ` changes in it. The peak memory is ~50%.

In both cases, the memory is taken by ycm process, but in case of vscode it takes 5x more.

**Comment by richard1122** [comment]
It might be very difficult for me to debug this problem due to I'm not familiar with YCMD server.
When I developing this extension, I tried to make this working the same as vim version with you complete me vim plugin source code.

**Comment by agauniyal** [comment]
I know that vim plugin uses completion and lint, this plugin uses those 2 also. Is there anything else that this plugin uses by default? Also I'm using the `ycmd.use_imprecise_get_type: true`, but that shouldn't interfere right?

**Comment by richard1122** [comment]
I even don't know what really interfere this problem.
You may have a look at https://github.com/richard1122/vscode-youcompleteme/blob/master/server/src/ycm.ts from line 205 to 275 .

There are many kind of requests, some of them are documented, some are not.
Some api like `BufferVisit`, `CurrentIdentifierFinished`, `InsertLeave` are used because I want to make this extension the same as what VIM version doing.

There are not too many things we can do in client side, ycmd does most of things automatically and we just send some files, get completion results, etc.

I really think we should discuss with ycmd developers, no matter whether this is a bug of ycmd. Or just this extension uses wrong API call. 

It's abnormal for ycmd to consume such high memory for the same project.

**Comment by agauniyal** [comment]
Okay I'm opening a new issue in YCMD repo and link this issue there.

**Comment by agauniyal** [comment]
Done here - https://github.com/Valloric/ycmd/issues/740
